### ISSUE TITLE
Explain each file in demo

### ISSUE THREAD

**Issue by gobengo** [fanout/fanout-graphql-tools#22]
"I'm surprised apollo-demo is over 1000 lines even when tests are excluded. Can you explain to me what is going on in each file for my own learning?"

**Comment by gobengo** [comment]
Talking about this other repo: https://github.com/fanout/apollo-serverless-demo

```
bengo@LAPTOP-9VBP4TSS:~/dev/fanout/apollo-demo$ find src/
src/
src/@types
src/@types/aws-serverless-express
src/@types/aws-serverless-express/index.d.ts
src/@types/aws-serverless-express/middleware.d.ts
src/@types/aws-serverless-express/package.json
src/@types/killable
src/@types/killable/index.d.ts
src/ApolloLambdaContextFromPulumiContext.ts
src/examples
src/examples/apollo-server-express-api.ts
src/examples/http-request-listener-api.ts
src/examples/http-server-api.ts
src/FanoutGraphqlApolloConfig.ts
src/FanoutGraphqlAppLambdaCallback.ts
src/FanoutGraphqlAppLambdaCallbackTest.test.ts
src/FanoutGraphqlAwsApp.ts
src/FanoutGraphqlExpressServer.ts
src/FanoutGraphqlExpressServerTest.test.ts
src/index.ts
src/observable-tools.ts
src/test
src/test/cli.ts
src/test/testFanoutGraphqlAtUrl.ts
src/test/unit.ts
src/WebSocketApolloClient.ts
```

src/ - typescript source files

src/@types - TypeScript declaration root (configured in tsconfig.json). When I used libraries that didn't have typescript declaration files, I added theme here.

src/@types/aws-serverless-express - type declarations for aws-serverless-express
src/@types/killable - type declarations for killable

src/ApolloLambdaContextFromPulumiContext.ts - The types of Pulumi's Lambda Context and that of the apollo-graphql-lambda EventHandler are very slightly different. This converts from the former to the latter so the typescript compiler is happy.

src/examples - Example subpackages. See each README
src/examples/apollo-server-express-api.ts
src/examples/http-request-listener-api.ts
src/examples/http-server-api.ts


src/FanoutGraphqlApolloConfig.ts - This is a constructor for a config object that can be passed to ApolloServer, and that configures that GraphQL API Server to have the 'notes' API that other components (e.g.) tests rely on. This config includes the graphql typeDefs,resolvers.

src/FanoutGraphqlAppLambdaCallback.ts - Create a function that can be used as an AWS Lambda Callback (with AWS' request event type). The function has the functionality of serving a GraphQL API configured by FanoutGraphqlApp.

src/FanoutGraphqlAppLambdaCallbackTest.test.ts - Unit test FanoutGraphqlAppLambdaCallback (`npm test` finds this, or you can execute the file as a script)

src/FanoutGraphqlAwsApp.ts - Constructor for object that represents an app composed of several @pulumi/aws resources. The app serves a GraphQL API via a Lambda, stores data in DynamoDB, has a periodic cleanup job, etc.

src/FanoutGraphqlExpressServer.ts - constructs an express Application that serves the FanoutGraphql API. This constructor is a bit complex because it tries to only configure the GraphQL Server to advertise support for subscriptions if the request is coming in via a WebSocket-Over-Http gateway. This is useful because if you just access the app lambda directly without a gateway, there is no way for the fanout-graphql-tools-powered subscriptions to work. Execute this script to create the server with default config and listen on an open HTTP port.

src/FanoutGraphqlExpressServerTest.test.ts - test FanoutGraphqlExpressServer. Includes some edge cases that are useful regression tests.

src/index.ts - Pulumi entrypoint (by default when running `pulumi up`). Creates a FanoutGraphqlAwsApp.

src/observable-tools.ts - module used for testing the Observable objects used by apollo-client

src/test - modules to help with testing.
src/test/cli.ts - Tool I often use to use alsatian as a library to run test suites it finds in the src dir.
src/test/testFanoutGraphqlAtUrl.ts - A test scenario that the test suite uses to test FanoutGraphql API is working right. The test suite calls this separate times to test the app directly via HTTP, through a pushpin server, etc.
src/test/unit.ts - `npm test` runs `ts-node ./src/test/unit`. This delegates to ./cli to find tests in ./src and run them.

src/WebSocketApolloClient.ts - quick module used by the test suite when creating an ApolloClient that does subscriptions via WebSocket.

Pulumi.dev.yaml - config for the 'dev' pulumi stack
Pulumi.prod.yaml - config for the 'prod' pulumi stack
tsconfig.json - configures the typescript compiler `tsc` (./node_modules/.bin/tsc)
tslint.json - configures tslint for style checking `npm run tslint`

**Comment by gobengo** [comment]
@jkarneges Wall of text above but it should include a description for each file. What do you think?

**Comment by jkarneges** [comment]
Thanks, this was helpful.
